/* generated by  http://json2ts.com/*/
declare module rawData {

    /** Demos  **/
    export interface Figure {
        path: string;
    }

    export interface Demos {
        name: string;
        figures: Figure[];
    }

    /** Description **/
    export interface Title {
        en: string;
        zh: string;
    }

    export interface Year {
        en: number;
        zh: number;
    }

    export interface CourseIntro {
        en: string;
        zh: string;
    }

    export interface CourseDesc {
        en: string;
        zh: string;
    }

    export interface Aims {
        en: string[];
        zh: string[];
    }

    export interface RequestDesc {
        en: string;
        zh: string;
    }

    export interface RequestContents {
        en: string[];
        zh: string[];
    }

    export interface Description {
        title: Title;
        year: Year;
        courseIntro: CourseIntro;
        courseDesc: CourseDesc;
        aims: Aims;
        requestDesc: RequestDesc;
        requestContents: RequestContents;
    }

    /********* Gallery ***********/
     export interface Gallery {
        title: string;
        src: string;
    }

    /********* Profiles ***********/
    export interface Instructor {
        en: string;
        zh: string;
    }

    export interface Assistant {
        en: string;
        zh: string;
    }

    export interface Profiles {
        instructors: Instructor[];
        assistants: Assistant[];
    }

    /********* Projects ***********/
    export interface Zh {
        content: string;
        start: string;
        end: string;
    }

    export interface Data {
        zh: Zh[];
    }

    export interface Notes {
        zh: string[];
    }

    export interface Projects {
        data: Data;
        notes: Notes;
    }

    /********* References ***********/
    export interface References {
        name: string;
        authors: string[];
        pub: string;
        pubYear: number;
        chinese: string;
    }
}